- notus/scanner/errors.py
- notus/scanner/loader/csv.py
- notus/scanner/loader/loader.py
- notus/scanner/scanner.py
**What**:
Change the loader to load the package advisories for an operating system. Raise new exception of advisories couldn't be loaded.
**Why**:
Make the loading of advisories more robust against failures and update loading interface for the future JSON files.
SC-362
**How**:
**Checklist**:
- n/a Tests
- n/a [CHANGELOG](https://github.com/greenbone/notus-scanner/blob/master/CHANGELOG.md) Entry
- n/a Documentation
> Improve loading of advisories

- notus/scanner/cli/parser.py
- notus/scanner/scanner.py
- notus/scanner/tools/scanstart.py
- notus/scanner/tools/subscriber.py
- pyproject.toml
**What**:
Add a notus-start-scant and notus-subscriber tools for testing the notus-scanner functionality.
* notus-start-scan allows to issue a scan start message that initiates the notus scan.
* notus-subscriber prints the status and result messages issued by the notus scanner
SC-365
**Why**:
Easier testing and debugging.
**How**:
**Checklist**:
> Add scripts for testing the notus-scanner functionality

- notus/scanner/messages/start.py
- tests/messages/test_start.py
- tests/messaging/__init__.py
- tests/messaging/test_mqtt.py
**What**:
Use "scanner/package/cmd/notus" from the latest spec.
SC-370
**Why**:
It has been adjusted to fit better into the eulabeia topic schema.
**How**:
**Checklist**:
> Adjust the start scan message topic

- README.md
- notus/scanner/errors.py
- notus/scanner/models/package.py
- notus/scanner/models/rpm.py
- tests/models/test_package.py
**What**:
Use our own rpm compare module for rpm package version comparisons instead of the python-rpm package. python-rpm is a binary package and not available via PyPI. Therefore it can't be used on all platforms and systems.
SC-412
**Why**:
python-rpm has serious downsides. Therefore replace it with a full Python module for package version comparisons.
**How**:
**Checklist**:
> RPM compare

- notus/scanner/models/package.py
- tests/models/test_package.py
**What**:
Strip the architecture string before resolving it into a Enum.
**Why**:
For some reason, when parsing package information, the architecture string contained an invisible `\r` at the end. The `strip()` method will remove it, if this is the case.
**How**:
**Checklist**:
> Fix: strip architecture string before resolving

- notus/scanner/messaging/mqtt.py
**What**:
Fix `on_disconnect` of mqtt module.
**Why**:
When the mqtt broker shuts down while the notus-scanner is running a error occurs:
```
TypeError: on_disconnect() takes from 2 to 3 positional arguments but 4 were given
```
**How**:
1. Start broker
2. Start notus-scanner
3. Stop broker
**Checklist**:
> Fix: on_disconnect method for mqtt

- notus/scanner/daemon.py
- notus/scanner/errors.py
- notus/scanner/loader/gpg_sha_verifier.py
- notus/scanner/loader/json.py
- notus/scanner/messages/message.py
- notus/scanner/messages/start.py
- notus/scanner/messages/status.py
- poetry.lock
- pyproject.toml
- tests/loader/test_gpg.py
- tests/loader/test_json.py
- tests/messages/test_message.py
- tests/messages/test_result.py
- tests/messages/test_start.py
- tests/messages/test_status.py
This adds a gpg verification when loading advisories; the gpg loading
has the assumptions that:
1. there is a sha256sum file within the advisories dir
2. there is a sha256sums.asc signature within the advisories dir
3. the public key to verify is already known to gpg
It is first loading the sha256sums file and parsing it to a Dict when
successful then it is creating a verify functions based on that dict
which will then be given to the json loader.
With this approach the gpg verifications needs to be done once while the
periodically called start scan is using a cache.
> Add: gpg verification when loading advisories

- README.md
- notus/scanner/loader/gpg_sha_verifier.py
- poetry.lock
**What**:
Use the same directory as openvas-scanner for loading the gnupg keys by
default. Additionally rename the env variable GPG_HOME to GNUPGHOME to
use the same variable as the gnupg project.
SC-476
**Why**:
**How**:
**Checklist**:
> Use /etc/openvas/gnupg for gnupg home as default

- notus/scanner/models/packages/deb.py
- notus/scanner/models/packages/package.py
- notus/scanner/models/packages/rpm.py
- tests/models/packages/test_rpm.py
**What**:
Ensure that the architecture is considered when comparing RPM packages.
SC-478
**Why**:
Packages with different architectures are not comparable.
**How**:
**Checklist**:
> Fix RPM package comparision with different architectures

- notus/scanner/messages/message.py
- tests/messages/test_message.py
- tests/messages/test_result.py
- tests/messages/test_start.py
- tests/messages/test_status.py
**What**:
Fill group_id with an uuid, when none is given.
**Why**:
ospd-openvas expects an uuid in the group_id field. In case none was given ospd-openvas was unable to parse the message.
**How**:
**Checklist**:
> Fix: set uuid for group_id

- .github/workflows/container.yml
**What**:
notus-scanner is a public project therefore the container images should
also be published on dockerhub. Additionally use our
container-image-tags action to use a consistent container naming.
**Why**:
All container images of public repos should be published at hub.docker.com.
**How**:
**Checklist**:
> Publish notus-scanner container on dockerhub

- notus/scanner/messages/result.py
- tests/messages/test_result.py
To make it easier to find notus results adjust the topic to
scanner/scan/info. This makes it easier to sport notus messages in a
different scan management environment than ospd.
> Refactor: change topic from scanner/results to scanner/scan/info

- notus/scanner/errors.py
- notus/scanner/loader/json.py
- notus/scanner/messages/message.py
- notus/scanner/messages/result.py
- notus/scanner/messages/start.py
- notus/scanner/messaging/mqtt.py
- notus/scanner/models/packages/package.py
- notus/scanner/scanner.py
- tests/loader/invalid_package.notus
- tests/loader/test_json.py
- tests/messages/test_message.py
- tests/messages/test_result.py
- tests/messages/test_start.py
- tests/messages/test_status.py
- tests/messaging/test_mqtt.py
**What**:
This PR improves the error handling to prevent it from crashing during scans.
SC-366
**Why**:
To improve the stability of the notus-scanner
**How**:
Using a MQTT tool to send scan start scan messages to the notus-scanner. I used MQTT explorer, but Mosquitto also comes with some command line tools.
Acceptance Criteria:
- It should be possible to issue a start scan message with an unknown or missing OS release without crashing notus-scanner
- It should be possible to issue a start scan message with missing package list without crashing notus-scanner
- Corrupt package names in the package list of the start scan message must be ignored
- Missing required information in all messages must be logged and the messages must be ignored
- Failures during the MQTT communication must not …
> Add: error handling, prevent notus from stopping

- notus/scanner/messages/message.py
- tests/messages/test_message.py
- tests/messages/test_result.py
- tests/messages/test_start.py
- tests/messages/test_status.py
To prevent failures when notus will be integrated into eulabeia the
parsing of group_id to uuid is getting dropped according to:
https://github.com/greenbone/eulabeia/blob/main/docs/messaging.md
> Refactor adjust group_id as defined in eulabeia

- README.md
- notus/scanner/cli/parser.py
- notus/scanner/config.py
- notus/scanner/daemon.py
- tests/cli/test_cli_parser.py
On a test system it is desireable to disable hashsum verification to
make changes without having to create sha256sums and sign it.
> Add: possibility to disable product hashsum verification

- pyproject.toml
The pyproject did not contain the packaging as well as tomli definition
and was therefore missing both in the docker image.
Unfortunately due to the dependency on pontos both versions needed to be
pinned down.
> Fix: docker image by adding tomli, packaging

- notus/scanner/loader/json.py
- notus/scanner/models/packages/package.py
- notus/scanner/scanner.py
- tests/fakespecifier_os.notus
- tests/models/packages/test_package.py
- tests/test_verifier.py
This commits adds the possibility to control verify statements by
adding a specifier to the fixed_packages:
```
{
"name": null,
"full_version": null,
"full_name": "xorg-x11-server-1.7.6.src",
"specifier": "<"
},
```
Defined specifiers are:
- `<` packages smaller than specified version are fixed
- `>` packages greater than specified version are fixed
- `<=` packages smaller or equal than specified version are fixed
- `>=` packages greather or equal than specified version are fixed
- `=` packages equal to specified version are fixed
When no specifier is added than it defautls to `>=`.
> Add: possibility to add range for packages

- notus/scanner/models/packages/deb.py
- notus/scanner/models/packages/rpm.py
**What**:
Remove white spaces before parsing package versions.
**Why**:
openvas is sending an invisible `\r` character at the end of each package. This lead to a false positive comparison if installed and fixed version were equal.
**How**:
**Checklist**:
> Fix: false positive for equal deb versions

- notus/scanner/models/vulnerability.py
- notus/scanner/scanner.py
- tests/models/test_vulnerability.py
- tests/test_verifier.py
**What**:
Combine multiple package vulnerabilities which belong to the same OID into a single result.
SC-504
**Why**:
The notus-scanner changed the behavior in which results are presented to the client. This lead to confusion, as multiple results with the same name showed up in the client. This could confuse users, as they seem like duplicated results. With this PR results are presented again as they should.
**How**:
Run a Full and Fast scan to see if results are presented as they should.
**Checklist**:
> Change: pack vulnerabilities from same OID in single result

- .docker/entrypoint.sh
- .docker/notus-scanner.Dockerfile
- .dockerignore
**What**:
Use an entrypoint script to switch to notus user
**Why**:
By using an entrypoint script with gosu to switch to the notus user for
running the notus-scanner it allows for becoming root and changing
the container more easily.
**How**:
**Checklist**:
> Use an entrypoint script to switch to notus user

- .docker/notus-scanner.Dockerfile
**What**:
The container assumes the default /var/lib/notus directory for the feed
content. This directory must have the correct access rights for being
able to sync the notus files from the feed.
**Why**:
Can't sync the feed when /var/lib/notus is owned by root.
**How**:
**Checklist**:
> Create and set directory permissions for feed content

- .docker/notus-scanner.Dockerfile
**What**:
Port of #232
The container assumes the default /var/lib/notus directory for the feed
content. This directory must have the correct access rights for being
able to sync the notus files from the feed.
**Why**:
Can't sync the feed when /var/lib/notus is owned by root.
**How**:
**Checklist**:
> Create and set directory permissions for feed content (Port #232)

- .mergify.yml
**What**:
Add mergify config to allow backporting changes from stable to main and
main to stable.
Backport of #258
**Why**:
**How**:
**Checklist**:
> Allow backporting PRs automatically via mergify (port #258)

- notus/scanner/daemon.py
**What**:
Notus-scanner exits now with a log message instead of an exception
SC-650
**Why**:
In case no MQTT broker was running, the notus-scanner would end with a `ConnectionRefuseError` as a exception. Now a log message is printed instead
**How**:
Start notus-scanner without having a MQTT broker running
**Checklist**:
> Fix: ConnectionRefusedError on startup when no broker is running

- notus/scanner/models/packages/__init__.py
- notus/scanner/models/packages/package.py
- notus/scanner/models/packages/slackware.py
- tests/models/packages/test_rpm.py
- tests/models/packages/test_slackware.py
**What**:
Add support for slackware packages
SC-637
**Why**:
**How**:
Start a scan on a slackware machine. Example for `gvm-cli`:
`gvm-cli --log DEBUG --timeout 3600 --protocol OSP socket --socketpath /home/osp/gb/var/run/ospd/ospd-openvas.sock scan.xml --pretty`
```xml
<start_scan scan_id='97079ee9-8917-49da-aa4f-4ef95f757ac1'>
<scanner_params>
<table_driven_lsc>1</table_driven_lsc>
</scanner_params>
<vt_selection>
<vt_single id='1.3.6.1.4.1.25623.1.0.50282'>
</vt_single>
</vt_selection>
<targets>
<target>
<hosts>127.0.0.1</hosts>
<ports>80,8080,443,22,2222</ports>
<credentials>
<credential service="ssh" type="up" port="2222">
<username>demo</username>
<password>demo</password>
</credential>
</credentials>
</target>
</targets>
<scanner_params>
</scanner_params>
</start_scan>
``` …
> Add: support for slackware packages

- .github/workflows/smoketests.yml
- smoketest/Dockerfile
- smoketest/Makefile
- smoketest/README.md
- smoketest/cmd/tests/main.go
- smoketest/gatherpackagelist-c18bb781-3740-44c2-aa01-1b73a00066e8.xml
- smoketest/go.mod
- smoketest/go.sum
- smoketest/hosts.txt
- smoketest/products/gatherpackagelist.go
- smoketest/products/init.go
- smoketest/redis.conf
- smoketest/scripts/start.sh
Notus smoketests are very simple test cases to verify the core functionality of Notus.
It is not meant to be fine granular tests but rather if the overall flow:
```
ospd-openvas -> openvas -> gatherpackagelist.nasl -> notus
```
is functioning.
Currently this is tested for
- Slackware 15
To add new images as a target you have to
- create a new target in the Makefile to spwan the new host
- create a new target to delete the new host
- adapt hosts.txt with the hostname username and password in the form us: `user:pass@host` in a new line
There are some requirements for a test image:
1. the image must have advisories and products defined in `/var/lib/notus` for the vulnerabilities of the image
1. the image must start an ssh server with a known username and password to login
> Add: smoke test for slackware packages

- notus/scanner/models/packages/package.py
- notus/scanner/models/vulnerability.py
- notus/scanner/scanner.py
- smoketest/products/init.go
- tests/models/packages/test_package.py
- tests/models/test_vulnerability.py
- tests/test_verifier.py
**What**:
The specifier is a tool to specify the comparison between packages. This leads to confusing results, as the specifier will not appear in the result, so results with the same installed and fixed version will be possible. To fix this, the specifier will be part of the report of the result and is contained in the fixed version. Example: `{ "name": null, "full_version": null, "full_name": "slackpkg-15.0.10-noarch-1", "specifier": ">"}` can lead to the result
Vulnerable package: slackpkg
Installed version:  slackpkg-15.0.10-noarch-1
Fixed version:      slackpkg-15.0.10-noarch-1
This will be fixed to:
Vulnerable package: slackpkg
Installed version:  slackpkg-15.0.10-noarch-1
Fixed version:      >slackpkg-15.0.10-noarch-1
SC-674
**Why**:
**How**:
**Checklist**:
> Add: specifier to the report of the result

- notus/scanner/models/packages/deb.py
- tests/models/packages/test_deb.py
**What**:
In some cases the comparison for Debian packages was not correct, as the single parts of the version were not compared part by part, but as a whole. This lead to false positive results as e.g.:
`2.7.15-4ubuntu4~18.04` was reported to be older then `2.7.15~rc1-1ubuntu0.1`, even though in this case it is the other way around. This PR will fix this issue.
SC-677
**Why**:
**How**:
**Checklist**:
> Fix: False positive Debian Package Comparison

- notus/scanner/models/packages/deb.py
- tests/models/packages/test_deb.py
**What**:
In case the name of a package contained a `-`, like apport-symptoms-0.20 it was parsed to Name: apport
Full Version: symptoms-0.20
even though symptoms is part of the name.
This was the case beacause of a small mistake within the regular expression, which did not check if the version starts with a number, which is necessary for Debian packages.
Now the package will be parsed to
Name: apport-symptoms
Full version:0.20
SC-682
**Why**:
**How**:
**Checklist**:
> Fix: parsing for debian packages with a - in the name

- notus/scanner/models/packages/rpm.py
- tests/models/packages/test_rpm.py
**What**:
In some cases RPM package versions containing a '.ksplice' or a '_fips' string. These versions are not comparable with other Versions missing this string.
SC-690
**Why**:
**How**:
**Checklist**:
> Fix: RPM package comparison by adding exceptions for version

- notus/scanner/models/packages/deb.py
- notus/scanner/models/packages/ebuild.py
- notus/scanner/models/packages/package.py
- notus/scanner/models/packages/rpm.py
- notus/scanner/models/packages/slackware.py
- tests/models/packages/test_deb.py
- tests/models/packages/test_package.py
- tests/models/packages/test_rpm.py
- tests/models/packages/test_slackware.py
**What**:
The Version module of packaging.version is meant to store the Version of python packages. This now lead to a problem, in which part of the Version, which was parsed was transformed, e.g. `1.1.1c` was parsed as `1.1.1rc0` which resulted in a false positive vulnerability detection. This is fixed with this PR.
SC-691
**Why**:
**How**:
**Checklist**:
> Refactor: use own version comparison instead of packaging.version

- notus/scanner/models/packages/deb.py
- notus/scanner/models/packages/ebuild.py
- notus/scanner/models/packages/package.py
- notus/scanner/models/packages/rpm.py
- notus/scanner/models/packages/slackware.py
- notus/scanner/scanner.py
- tests/fakespecifier_os.notus
- tests/test_verifier.py
_check_package was returning when the check for a vulnerability is
negative that meant that if there were multiple architectures defined it
returns None although the wanted architecure in the list was not reached
yet.
In return there were missing vulnerabilities, this is fixed by changing
it to continue and verify on _start_scan if vulnerabilities within
vulnerability were found instead of relying on None.
> Fix: _check_package returns None although there are vulnerabilities

- notus/scanner/models/packages/package.py
- tests/models/packages/test_package.py
**What**:
A small bug lead to a wrong version comparison in case one of the versions contained a `~` at the same position the other version contains a letter. In this case the version given first was always declared to be newer. This issue is fixed with this PR and a test is added for such a case.
SC-752
**Why**:
**How**:
Compare two versions such as `20211016ubuntu0.20.04.1` with `20211016~20.04.1`. The first should be always newer. In the old unfixed version the one used as base to compare was always newer.
This can be tested in the python shell:
```python
from notus.scanner.models.packages.package import Package
version_compare("20211016~20.04.1", "20211016ubuntu0.20.04.1")
version_compare("20211016ubuntu0.20.04.1", "20211016~20.04.1")
``` 
The above example is fixed with the new patch …
> Fix: version comparison in case of an `~`

- notus/scanner/config.py
- pyproject.toml
**What**:
utilise tomllib over tomli for python3.11 and greater
**Why**:
avoids a dependency for newer python versions as it is part of the stdlib
**How**:
load toml config
**Checklist**:
> Change: Use `tomllib` for Python 3.11 and greater

- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
**What** & **Why**:
Instead of using greenbone/release-python@v2 we should switch to use greenbone/release@v2 everywhere, so we only need to maintain one release action.
Remove PR_TEMPLATE
**How**:
Magic. DEVOPS-539
**Checklist**:
> Change: Use universal release action, not python specific

- notus/scanner/utils.py
Only use file logging handler if log file is set
Don't crash if no log file is passed when stating notus-scanner.
#418
> Fix: Only use file logging handler if log file is set

- INSTALL.md
- Usually it`s Debian, not debian.
- No template or changelog entry for such a minor text change
> Install: Change "debian" to "Debian" in one description

- INSTALL.md
- Additional default path fix as a follow-up to #229
- See https://github.com/greenbone/notus-scanner/blob/67460623d1929c95b6fcf6b37986a9492ce1baf5/notus/scanner/config.py#L65 for the `false` default
- In the link above `False` can be seen but the example in https://github.com/greenbone/notus-scanner/blob/9c5588e43b25609db13033d6a373bb97d52a7ea0/INSTALL.md#configuration shows `false` so i took the latter. If `False` (uppercace `F`) is more correct it would need to be updated there as well
More correct / consistent info
N/A
> Fix: Missing default value and wrong default path in INSTALL.md

- tests/models/packages/gentoo_examples.txt
- tests/models/packages/test_ebuild.py
Remove a wrong line from the example list for gentoo and fix the test to run over the whole file
There was a strange line which seems not to be a package name.
It was only running on the first line in the file. Now parses all lines in the file
> Fix: ebuild tests

- notus/scanner/cli/parser.py
- notus/scanner/config.py
- notus/scanner/daemon.py
Support authenticated connection to MQTT broker
If notus-scanner options --mqtt-broker-user and `--mqtt-broker-password are given (or configured in the notus-scanner.toml configuration file), the connection will be authenticated. For this to work, MQTT broker must be configured with valid user and pass. This is disable per default.
SC-917
Improvement
> Add: Support authenticated connection to MQTT broker

- notus/scanner/messaging/mqtt.py
- poetry.lock
- pyproject.toml
Support paho-mqtt version 1 and 2
For GOS we want to keep compatibility to paho-mqtt 1 but Kali for example already has switched to version 2. Therefore support both versions.
> Change: Support paho-mqtt version 1 and 2

- .github/workflows/ci-python.yml
Fix: Use `ruff check` as linter
Using `ruff` is deprecated ...
DEVOPS-1093
> Fix: Use `ruff check` as linter

- pyproject.toml
Adjust the settings for ruff in the pyproject.toml,  Please update the following options in `pyproject.toml`:
'extend-select' -> 'lint.extend-select'
'ignore' -> 'lint.ignore'
'per-file-ignores' -> 'lint.per-file-ignores'}}
.. to prevent the printing of:
{{warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section.
[DEVOPS-1116](https://jira.greenbone.net/browse/DEVOPS-1116)
> Fix: update pyproject ruff settings

- notus/scanner/models/packages/deb.py
- tests/models/packages/test_deb.py
The parsing inside notus scanner was done wrong in some cases, as the following example shows. Here a package with full name including the version of the installed package:
```
mariadb-server-10.6-1:10.6.18+maria~ubu2204
```
which should separate name and version into:
```
name: mariadb-server-10.6
version: 1:10.6.18+maria~ubu2204
```
but resulted in:
```
name: mariadb-server
version: 10.6-1:10.6.18+maria~ubu2204
```
which is not even a valid version at all.
Updating the regular expressions fixes this issue.
This issue came up in https://forum.greenbone.net/t/ubuntu-22-04-lts-mariadb-server-false-positive/18779
SC-1121
> Fix: notus deb package parsing

- notus/scanner/messages/result.py
Change: URI result field defaults now to an empty string instead of None
gvmd will ignore/hide the URI field if it is an empty string.
Jira: SC-1197
None was later serialized and sent as string containing "None" in the URI result field.
> Change: URI result field defaults now to an empty string instead of None

- notus/scanner/daemon.py
- notus/scanner/loader/gpg_sha_verifier.py
- notus/scanner/models/packages/package.py
- tests/cli/test_cli_parser.py
CI was failing in recent PRs, this fixes it.
> Fix CI: Run new version of black.
