greenbone/notus-scanner

- tests/models/test_vulnerability.py
**What**:
Add tests for the vulnerability model.
**Why**:
**How**:
**Checklist**:
> add tests for vulnerability model

- notus/scanner/daemon.py
- notus/scanner/loader/__init__.py
- notus/scanner/loader/csv.py
- notus/scanner/loader/json.py
- notus/scanner/models/advisory.py
- notus/scanner/scanner.py
- tests/loader/EulerOS_V2.0SP1.notus
- tests/loader/test_csv.py
- tests/loader/test_json.py
- tests/models/test_advisory.py
- tests/models/test_vulnerability.py
**What**:
Implement a new JSON based parser for loading the advisories.
SC-361
**Why**:
The new JSON format is much better suited for this kind of structured data then CSV. It is easier to parse and supports different types of data.
**How**:
**Checklist**:
> Implement JSON Parser

- .coveragerc
- .github/workflows/ci-python.yml
**What**:
Add config file for correct coverage calculation and install rpm package to allow running the Package comparison tests.
**Why**:
The coverage calculation included the tests and was missing a the __gt__ method of the Package class.
**How**:
**Checklist**:
> Improve coverage

- notus/scanner/loader/json.py
- notus/scanner/messages/start.py
- notus/scanner/messaging/mqtt.py
- notus/scanner/scanner.py
**What**:
Fix several mistakes and improve logging.
**Why**:
Without these fixes notus scanner will crash after receiving a scan start message.
**How**:
**Checklist**:
> Fixes for some mistakes

- notus/scanner/daemon.py
- notus/scanner/messaging/mqtt.py
- notus/scanner/messaging/publisher.py
- notus/scanner/messaging/subscriber.py
- notus/scanner/scanner.py
**What**:
Refactor the messaging module and MQTT classes.
**Why**:
The messaging module is no concerned with publishing and subscribing to messages. It doesn't know anything about concrete data anymore.
**How**:
**Checklist**:
> Messaging improvements

- notus/scanner/scanner.py
**What**:
Publish scan status running message when a scan for a host has started.
**Why**:
The client should be noticed about a scan start.
**How**:
**Checklist**:
> Scan status

- .docker/broker.Dockerfile
- .docker/docker-compose.yml
- .docker/notus-scanner.Dockerfile
**What**:
Use default MQTT port in containers
**Why**:
There is no need to use the alternative port.
**How**:
**Checklist**:
> Use default MQTT port in containers

- .github/workflows/ci-python.yml
- .github/workflows/container.yml
- .github/workflows/release-pontos.yml
**What**:
Remove installation of python3-rpm debian package and update to newest usage of our poetry action
**Why**:
**How**:
**Checklist**:
> Fix and update workflows

- notus/scanner/models/package.py
**What**:
Add support for new SuSE architecture.
SC-398
**Why**:
SuSE added a new package architecture for a 32-Bit on ARM 64-Bit architecture called aarch64_ilp32
**How**:
**Checklist**:
> Add: support for SuSE aarch64_ilp32 architecture

- notus/scanner/loader/json.py
**What**:
Fix package type selection.
**Why**:
DEBPackage was always selected as the Package Class
**How**:
**Checklist**:
> Fix: package type selection

- notus/scanner/models/packages/deb.py
- tests/models/packages/test_deb.py
**What**:
Fix the parsing of debian packages. Also added test to cover the fix
**Why**:
If the revision part of the version of a debian package was missing (which is allowed), notus ended with an exception.
**How**:
**Checklist**:
> Fix deb parsing

- .github/workflows/release-pontos-manually.yml
- .github/workflows/update-header.yml
- .pontos-header-ignore
**What**:
**Why**:
**How**:
**Checklist**:
> Update release workflows, add update-header workflow (testing)

- .pontos-header-ignore
**What**:
Don't update copyrights of deb and rpm packages because we don't own it.
**Why**:
**How**:
**Checklist**:
> Add ignore-files for header updates

- .docker/notus-scanner.Dockerfile
**What**:
gpg and gpg-agent are required to validate the feed signature.
**Why**:
**How**:
**Checklist**:
> Add gpg and gpg-agent to container image

- .docker/broker.Dockerfile
- .docker/docker-compose.yml
- .github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Cleanup docker build

- README.md
**What**:
**Why**:
**How**:
**Checklist**:
> Update copyright date in README

- INSTALL.md
- README.md
To describe how to install, configure and run Notus add a INSTALL.md
> Add: first version of INSTALL.md

- INSTALL.md
- config/notus-scanner.service
- Refactor: provide systemd-example, adapt example configuration (#227)
> systemd example into stable

- notus/scanner/messaging/mqtt.py
- poetry.lock
- pyproject.toml
**What**:
Don't exit with exception in case the MQTT connection is lost
Automatically subscribes again to all topics after a reconnect of MQTT
SC-649
GOS-1037
**Why**:
In case the ospd-openvas MQTT client disconnect from its broker, it exited with an exception due to a bug within the currently used paho-mqtt version. This issue is fixed with this PR
**How**:
Run ospd-openvas and notus-scanner. They should connect to a MQTT broker. After ospd-openvas is initialized stop the broker and restart it after a few seconds. Start a scan and watch for notus results. In the old version ospd-openvas should not be able to receive any. This PR fixes this issue. Note that ospd-openvas had a similar problem, which will get fixed with https://github.com/greenbone/ospd-openvas/pull/713
Start scan via …
> Fix mqtt connection

- notus/scanner/messaging/mqtt.py
- poetry.lock
- pyproject.toml
Backport of https://github.com/greenbone/notus-scanner/pull/239
> backport fix mqtt connection (#239)

- pyproject.toml
Refactor: move comment of list to variable because of toml bug
> Refactor: move comment of list to variable because of toml bug

- poetry.lock
**What**:
**Why**:
**How**:
**Checklist**:
> [main] Update dependencies

- poetry.lock
**What**:
**Why**:
**How**:
**Checklist**:
> [stable] Update dependencies

- poetry.lock
- pyproject.toml
**What**:
Fix several warning during installation on different distributions.
**Why**:
Get rid of installation warnings and specify better version ranges for our dependencies
**How**:
**Checklist**:
> Update dependency specification

- .mergify.yml
**What**:
Add mergify config to allow backporting changes from stable to main and
main to stable.
**Why**:
Make it easier to apply changes to different branches.
**How**:
**Checklist**:
> Allow backporting PRs automatically via mergify

- notus/scanner/loader/json.py
- notus/scanner/scanner.py
**What**:
Change: Extend logging when starting a scan
**Why**:
Allow for better debugging via log messages.
**How**:
**Checklist**:
> Change: Extend logging when starting a scan

- .github/workflows/container.yml
**What**:
Build notus-scanner container image for pull requests too
**Why**:
Ensure that changes in a PR don't break the container build.
**How**:
**Checklist**:
> Change: Build notus-scanner container image for pull requests too

- notus/scanner/loader/gpg_sha_verifier.py
Instead of just using GOS defaults `/etc/openvas/gnupg` check if the
directory exists and when not use `$HOME/.gnupg` instead.
If both are not available print a warning that the env variable
GNUPGHOME should be set but stick with the failing `$HOME/.gnupg` to
prevent None checking.
> Fix: use ~/.gnupg when /etc/openvas/gnupg is not available

- notus/scanner/scanner.py
**What**:
Re-implementing https://github.com/greenbone/notus-scanner/pull/262, which was removed by https://github.com/greenbone/notus-scanner/pull/292
**Why**:
**How**:
**Checklist**:
> Re-implementing logging when starting a scan

- .github/workflows/ci-python.yml
- README.md
Due to stability reason when uploading we decided to remove codecov.
> Change: remove codecov

- poetry.lock
**What**:
**Why**:
**How**:
**Checklist**:
> Update dependencies with poetry update call

- .github/workflows/ci-python.yml
**What**:
Update version of the greenbone actions
**Why**:
nodejs12 is deprecated
set-output command becomes deprecated
**How**:
**Checklist**:
> Change: update action versions

- .github/workflows/ci-python.yml
**What**:
Update version of the greenbone actions
SC-731
**Why**:
nodejs12 is deprecated
set-output command becomes deprecated
**How**:
**Checklist**:
> Change: update action versions stable

- notus/scanner/utils.py
**What**:
Don't crash if the pid file contains an invalid pid
Closes #363
jira: SC-748
**Why**:
When loading the pid from the pid file notus scanner shouldn't crash if the file is empty or contains non integer data.
**How**:
**Checklist**:
> Fix: Don't crash if the pid file contains an invalid pid

- .github/workflows/release-pontos-manually.yml
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: Choose branch for release branch workflow

- .github/workflows/ci-python.yml
- pyproject.toml
**What**:
Add support for Python 3.11
**Why**:
Run CI on Python 3.11 too and update project metadata to officially support Python 3.11.
#407
> Add: Add support for Python 3.11

- notus/scanner/scanner.py
- notus/scanner/utils.py
- poetry.lock
- pyproject.toml
**What**:
Only list direct development dependencies
Also update dependencies to latest versions.
**Why**:
Easier maintenance of the dependencies.
> Change: Only list direct development dependencies

- notus/scanner/utils.py
Log to file also when running in foreground
Allow for easier debugging of user issues even when running notus-scanner in foreground.
> Improve logging

- notus/scanner/daemon.py
- poetry.lock
- pyproject.toml
Remove: sentry support
Jira: SC-849
Not used
> Remove: sentry support

- notus/scanner/messages/message.py
- notus/scanner/models/packages/package.py
- poetry.lock
- pyproject.toml
Change: pin paho-mqtt version less than 2.0.
Jira: SC-1032
Use an alternative syntax to check if dependabot doesn't change it
> Change: pin paho-mqtt version less than 2.0.

- notus/scanner/models/packages/__init__.py
- notus/scanner/models/packages/package.py
- notus/scanner/models/packages/windows.py
- tests/models/packages/test_windows.py
> Add: Windows 11 and Server 2022 build comparison support
